OpenVADL/openvadl

- gradlew
- gradlew.bat
This PR introduces the following changes:
* set minimum required Java 17 major version fix in Gradle setup (relates to docs changed in a905882a450cc9ee53d4b7a42e98e2d2c30b8083)
> chore: Tooling Java Minimum Major Version Check

- vadl/main/vadl/ast/ViamLowering.java
- vadl/test/vadl/ast/ViamLoweringTest.java
Fixes #165
The new error message is
```
> Task :vadl-cli:run FAILED
error: Cannot find the pseudo return instruction
╭──[test.vadl:6:1]
│
6 │> application binary interface ABI for ISA = {
7 │>   alias register ra = X(0)
8 │>   alias register gp = X(1)
⋮  13 lines omitted here...
22 │>   pseudo return instruction = RET
23 │>
24 │> }
│
│
help: Maybe check if this instruction really exists or was spelled incorrectly?
```
> ast: Fixed error message when pseudo instruction was not found

- vadl/main/resources/templates/lcb/llvm/lib/Target/AsmPrinter.cpp
- vadl/main/resources/templates/lcb/llvm/lib/Target/MCTargetDesc/TargetMCCodeEmitter.cpp
- vadl/main/resources/templates/lcb/llvm/lib/Target/MCTargetDesc/TargetMCInstExpander.cpp
- vadl/main/resources/templates/lcb/llvm/lib/Target/MCTargetDesc/TargetMCInstExpander.h
- vadl/main/vadl/cppCodeGen/FunctionCodeGenerator.java
- vadl/main/vadl/cppCodeGen/common/AccessFunctionCodeGenerator.java
- vadl/main/vadl/cppCodeGen/common/AsmParserFunctionCodeGenerator.java
- vadl/main/vadl/cppCodeGen/common/PureFunctionCodeGenerator.java
- vadl/main/vadl/cppCodeGen/mixins/CDefaultMixins.java
- vadl/main/vadl/iss/passes/IssNormalizationPass.java
- vadl/main/vadl/iss/passes/tcgLowering/TcgOpLoweringPass.java
- vadl/main/vadl/lcb/codegen/expansion/CompilerInstructionExpansionCodeGenerator.java
- vadl/main/vadl/pass/PassOrders.java
- vadl/main/vadl/viam/graph/Graph.java
- vadl/main/vadl/viam/graph/control/NewLabelNode.java
- vadl/main/vadl/viam/graph/dependency/LabelNode.java
- vadl/main/vadl/viam/passes/HardcodeLGALabelPass.java
- vadl/test/resources/llvm/riscv/llvmIR/rv64im/O0/pic.ll
- vadl/test/resources/llvm/riscv/llvmIR/rv64im/O3/pic.ll
- vadl/test/vadl/lcb/riscv/riscv64/template/MCTargetDesc/EmitMCInstExpanderCppFilePassTest.java
This PR is temporary fix to hardcode the generation of label which is required in #148. This pass has to be deleted as soon as the parser can generate it automatically.
> viam: Hardcoded setting label for LGA

- vadl/main/resources/templates/lcb/llvm/lib/Target/MCTargetDesc/TargetInstPrinter.cpp
- vadl/main/vadl/ast/BehaviorLowering.java
- vadl/main/vadl/lcb/codegen/assembly/AssemblyInstructionPrinterCodeGeneratorVisitor.java
- vadl/main/vadl/lcb/codegen/expansion/CompilerInstructionExpansionCodeGenerator.java
- vadl/main/vadl/lcb/template/lib/Target/MCTargetDesc/EmitInstPrinterCppFilePass.java
- vadl/test/resources/llvm/riscv/asm/rv32im/codeemitter/PseudoInstructions.s
- vadl/test/resources/testSource/sys/risc-v/rv3264im.vadl
- vadl/test/vadl/lcb/riscv/riscv64/template/MCTargetDesc/EmitMCInstExpanderCppFilePassTest.java
This PR fixes the decoding bug described in #175 and an encoding bug in the assembly printer, which came to light after fixing the decoding issue.
> lcb: Fix pseudo expansion decoding and assembly printer encoding

- vadl/main/vadl/ast/Definition.java
- vadl/main/vadl/ast/TypeChecker.java
- vadl/test/vadl/ast/TypecheckerTest.java
Typechecking a reference to an enumeration field requires that the whole enumeration was already typechecked. Because the typechecker might set the value of the field if it is implicitly defined (no explicit value was assigned).
@Jozott00 I added you as a reviewer since git blame pointed to you as the author 😜
> typechecker: Fix crash typechecking enum field before enum definition

- vadl/main/vadl/ast/ParserUtils.java
- vadl/main/vadl/ast/vadl.ATG
Many people that started contributing to the parser got tricked by the confusingly named function `loc()` which only returned the location of the last consumed token instead of the more intuitive guess of the location of the whole rule.
The better naming should now make it much clearer what the functions do.
> parser: Improve location utility function naming

- vadl/main/vadl/gcb/passes/DetermineRelocationTypeForFieldPass.java
- vadl/main/vadl/gcb/passes/DetermineSymbolRelocationTypePass.java
- vadl/main/vadl/gcb/passes/RelocationKindCtx.java
- vadl/main/vadl/lcb/template/lib/Target/MCTargetDesc/EmitMCCodeEmitterCppFilePass.java
- vadl/main/vadl/pass/PassOrders.java
- vadl/test/resources/llvm/riscv/asm/rv32im/codeemitter/BType.s
- vadl/test/resources/llvm/riscv/asm/rv32im/codeemitter/PseudoInstructions.s
This PR adjusts the the `MCCodeEmitter` to emit the correct type of relocations when unknown symbols are used as immediate operands. If the instruction's behavior adds the immediate operand to the program counter, a relative relocation is emitted, else an absolute relocation is emitted.
> asm: Emit correct kind of relocations for unknown symbols

- vadl/test/vadl/gcb/AbstractGcbTest.java
- vadl/test/vadl/gcb/riscv/riscv64/GenerateValueRangeImmediatePassTest.java
- vadl/test/vadl/gcb/riscv/riscv64/IdentifyFieldUsagePassTest.java
- vadl/test/vadl/gcb/riscv/riscv64/passes/DetermineRelocationTypeForFieldPassTest.java
We already had a test with LLVM file check. However, this requires to compile LLVM. The test in this PR is faster and faster to execute. Additionally, it checks whether register fields have no compiler kind relocation.
> gcb: Added test for determining compiler kind

- vadl/test/resources/snapshots/rv64im/InstrInfoTableGen.td
- vadl/test/resources/testSource/sys/risc-v/rv64im.vadl
- vadl/test/vadl/lcb/riscv/riscv64/template/MCTargetDesc/EmitMCInstExpanderCppFilePassTest.java
Follow-up of !213, since it added a method which checks whether the immediate fits into i32. If it does not then use the constant pool. This made the constant materialisation in the spec obsolete.
> lcb: Removed obsolete constant materialisation for i64

- buildSrc/src/main/kotlin/vadl/CocoR.gradle.kts
- vadl/build.gradle.kts
- vadl/main/vadl/ast/Parser.frame
- vadl/main/vadl/ast/ParserUtils.java
Improves several error messages and refactors code duplication in the `ParserUtils`
If one wants to invoke a none defined macro, the parser states this now. Instead of
```
error: Parsing Error
╭──[file:///Users/jozott/development/uni/dipl/iss-dev/code/open-vadl/out/test.vadl:1:24]
│
1 │ model outer() : Id = { $inner() }
│                        ^ Expected node of type Id, received InvalidType - PlaceholderNode
│ 
The parser got confused at this point, probably because of a syntax error in your code.
```
we print
```
error: Parsing Error
╭──[file:///Users/jozott/development/uni/dipl/iss-dev/code/open-vadl/out/test.vadl:1:24]
│
1 │ model outer() : Id = { $inner() }
│                        ^ Macro $inner used but not yet defined
│ 
The parser got confused at this point, probably because of …
```
> parser: Improve error message

- sys/v-risc/VarRisc.vadl
The instruction set has a conflict for the `BAL` and `SYS` instruction (`opcode: 62`, `func5: 31`) which currently have the same instruction patterns
This looks to me like a mistake in the macro definition of `SysCallInstr`, which should use `opcode 61` (`MemCode`) according to the op/fun-code table in the comment.
I fixed it, but please check if that's the correct replacement opcode.
> sys:var-risc Fix opcode encoding of SYS insn

- vadl/main/vadl/vdt/passes/VdtLoweringPass.java
- vadl/main/vadl/vdt/utils/PatternUtils.java
- vadl/test/vadl/utils/codegen/StringBuilderAppendableTest.java
- vadl/test/vadl/vdt/utils/PatternUtilsTest.java
There was a problem when converting encodings of fixed fields into the corresponding bit pattern for the decoder generation algorithm.
For example this happened for instructions of the `AddSubExtFormat` format in the `AArch64` spec, where the `opcode` field is split across multiple bit slices.
> decoder: Fix issues with split bit splices encoding

- vadl/test/resources/embench/benchmark-extras/rv32-run-benchmarks-spike-clang-lcb-O0.sh
- vadl/test/resources/embench/benchmark-extras/rv32-run-benchmarks-spike-clang-lcb-O3.sh
- vadl/test/resources/embench/benchmark-extras/rv64-run-benchmarks-spike-clang-lcb-O0.sh
- vadl/test/resources/embench/benchmark-extras/rv64-run-benchmarks-spike-clang-lcb-O3.sh
- vadl/test/resources/embench/src/wikisort/libwikisort.c
The benchmark uses an include for <limits.h>.
The libc, which we are using, includes the limits.h from the host system which requires a glibc macro which is undefined. It's not clear to me why it is undefind but we actually don't need the <limits.h> include in the benchmark. The easiest fix is to remove it.
> lcb: Fixed wikisort benchmark

- vadl/main/vadl/ast/Definition.java
- vadl/main/vadl/ast/Expr.java
- vadl/main/vadl/ast/Ungrouper.java
- vadl/main/vadl/ast/vadl.ATG
- vadl/test/resources/dumps/rv64im.dump
- vadl/test/resources/macros/complex-types.expanded.vadl
- vadl/test/resources/macros/hexagon.expanded.vadl
- vadl/test/resources/macros/macro-producing-macros.expanded.vadl
- vadl/test/resources/macros/operators.expanded.vadl
- vadl/test/resources/macros/rv3264im.expanded.vadl
- vadl/test/vadl/ast/AstTestUtils.java
- vadl/test/vadl/ast/BinaryPrecedenceTest.java
- vadl/test/vadl/ast/FrontendIntegrationTest.java
- vadl/test/vadl/ast/ParserTest.java
Fixes a couple of pretty print issues:
- Unary operators #239
- Assembly grammar default rules
- ABI definitions
Additionally it adds a pretty print test for the rv32im spec.
> frontend: Fix pretty print

- vadl/main/vadl/ast/AstUtils.java
- vadl/main/vadl/ast/BehaviorLowering.java
- vadl/main/vadl/ast/Definition.java
- vadl/main/vadl/ast/Expr.java
- vadl/main/vadl/ast/Statement.java
- vadl/main/vadl/ast/SymbolTable.java
- vadl/main/vadl/ast/TypeChecker.java
- vadl/main/vadl/utils/GraphUtils.java
- vadl/main/vadl/viam/Constant.java
- vadl/main/vadl/viam/graph/dependency/ReadArtificialResNode.java
- vadl/main/vadl/viam/graph/dependency/ReadMemNode.java
- vadl/main/vadl/viam/graph/dependency/WriteArtificialResNode.java
- vadl/test/resources/testSource/sys/risc-v/rv3264im.vadl
- vadl/test/vadl/ast/CallIndexExprTest.java
- vadl/test/vadl/ast/ExceptionTest.java
- vadl/test/vadl/ast/FrontendIntegrationTest.java
This PR supports slices on assignments. 
For instance: 
```
A(1, 10..2) := someExpr()
A.myField := someExpr()
```
Additionally it completely refactors the typechecking and lowering of `CallIndexExpr`, which had a lot of code duplication, had limitations and was not generalized.
> frontend: Support slices on assignments

- vadl/main/vadl/dump/BehaviorTimelineDisplay.java
- vadl/main/vadl/dump/CollectBehaviorDotGraphPass.java
- vadl/main/vadl/dump/InfoUtils.java
- vadl/main/vadl/dump/infoEnrichers/LcbEnricherCollection.java
- vadl/main/vadl/dump/infoEnrichers/ViamEnricherCollection.java
- vadl/main/vadl/lcb/passes/llvmLowering/domain/LlvmLoweringRecord.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/LlvmInstructionLoweringStrategy.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/instruction/LlvmInstructionLoweringConditionalBranchesStrategyImpl.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/instruction/LlvmInstructionLoweringIndirectJumpStrategyImpl.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/instruction/LlvmInstructionLoweringUnconditionalJumpsStrategyImpl.java
- vadl/main/vadl/pass/PassResults.java
It is sometimes necessary to create multiple graphs based on the original viam graph. This PR adds the functionality s.t these graphs get also optimised. Additionally, they will be dumped so that a developer can see why a LLVM graph was not lowered properly.
For example, the ADDI has a VIAM behavior, a lowered LCB graph and an additional graph where the immediate is replaced by a frame index.
> lcb: Run the optimizer on derived graphs and enhance dumps

- vadl/main/vadl/dump/infoEnrichers/ViamEnricherCollection.java
With this, the pass timeline for a graph gets more readable and shorter + the whole dump is a lot smaller in size.
> dump: Filter only graph altering passes in the dump timeline

- vadl-cli/main/vadl/cli/CheckCommand.java
- vadl/main/vadl/ast/ViamLowering.java
- vadl/main/vadl/pass/PassOrders.java
- vadl/main/vadl/types/BuiltInTable.java
- vadl/main/vadl/vdt/impl/theiling/TheilingDecodeTreeGenerator.java
- vadl/main/vadl/vdt/passes/VdtLoweringPass.java
This PR lowers the root ISA, if there was no generator entry definition (such as `processor`) and a single root ISA could be determined.
Additionally the VDT generator is now executed on `check`, to validate that there are no overlapping instructions.
Currently, the VDT generator throws runtime exceptions if there are problems with the specification. @rascmatt will fix this by throwing detailed diagnostic user errors.
> cli: Add default ISA lowering of root ISA

- vadl/main/vadl/ast/ParserUtils.java
- vadl/main/vadl/utils/Leivenshtein.java
The error message now sorts the available basic syntax types according to their Levenshtein distance (edit distance).
The added infrastructure can be added in the future to all other kinds of not found variables, instructions and so on though the symboltable needs to be expanded to return all known variables in a given scope.
```
model three() : Expr = {
1 + 2
}
```
**Before:**
```
error: Unknown syntax type: `Expr`
╭──[file:///Users/flo/src/open-vadl/tmp.vadl:1:17]
│
1 │ model three() : Expr = {
│                 ^^^^ No syntax type with this name exists.
│ 
help: Maybe you meant to use one of the following:
Stats, Stat, Encs, Defs, IsaDefs, Ex, Lit, Str, Val, Bool, Int, Bin, CallEx, SymEx, Id, BinOp, UnOp
```
**After:**
```
error: Unknown syntax type: `Expr` …
```
> parser: Rank suggestions for invalid syntax types error message based on edit distance.

- .github/workflows/build-aarch64-toolchain.yml
- .github/workflows/build-qemu-aarch64.yml
- docker/iss/aarch64-toolchain/Dockerfile
- docker/iss/aarch64-toolchain/README.md
- docker/iss/qemu-aarch64/Dockerfile
- docker/iss/qemu-aarch64/README.md
- docker/iss/qemu-riscv64/README.md
This PR adds an image for aarch64 qemu and an image with an aarch64 toolchain (bare metal and linux gnu).
> ci: Added aarch64 images

- vadl/main/vadl/cppCodeGen/common/AccessFunctionCodeGenerator.java
- vadl/main/vadl/cppCodeGen/common/GcbAccessOrExtractionFunctionCodeGenerator.java
- vadl/main/vadl/lcb/template/superClass/AbstractEmitImmediateFilePass.java
- vadl/main/vadl/vdt/target/iss/IssDecisionTreeCodeGenerator.java
- vadl/main/vadl/viam/Format.java
- vadl/test/vadl/cppCodeGen/EncodingCodeGeneratorCppVerificationTest.java
- vadl/test/vadl/lcb/riscv/riscv64/verification/ImmediateExtractionCodeGeneratorCppVerificationRiscv64Test.java
Until now, we assumed that there is exactly one field a field access is referring to. 
However, there might be multiple fields referenced in a single field access. E.g. the AArch64 spec defines
```
format BitFieldMoveFormat: Instr =  // bit field move format
{ ...
, immr       : Bits6              // rotate right count (bit field low position)
, imms       : Bits6              // bit field length -1 or high position
, ...
, rightWSize = BitfieldRightWSize (imms(4..0), immr(4..0))
, rightXSize = BitfieldRightXSize (imms, immr)
}
```
The `Format.FieldAccess` VIAM definition now holds a list of field references (instead of a single one). The `fieldRef()` method is still available as we currently don't have a good way to handle multiple field references in the LCB.
Additionally, the decoder …
> viam: Allow multiple field references in FieldAccess

- docs/refman/refmanual.md
- vadl/main/resources/templates/common/vadl-builtins.h
- vadl/main/vadl/iss/passes/IssNormalizationPass.java
- vadl/main/vadl/types/BuiltInTable.java
- vadl/main/vadl/utils/VadlBuiltInEmptyNoStatusDispatcher.java
- vadl/main/vadl/utils/VadlBuiltInNoStatusDispatcher.java
- vadl/main/vadl/viam/Constant.java
- vadl/test/vadl/cppCodeGen/BuiltinCTest.java
Adds the `CTZ` and `CTO` built-ins.
```
function ctz( a : Bits<N> ) -> UInt<N> // counting trailing zeros
function cto( a : Bits<N> ) -> UInt<N> // counting trailing ones
```
This closes #278.
> language: Add CTZ and CTO built-ins

- vadl/main/vadl/lcb/template/clang/lib/Basic/Targets/EmitClangTargetCppFilePass.java
- vadl/main/vadl/lcb/template/clang/lib/Basic/Targets/EmitClangTargetsFilePass.java
- vadl/main/vadl/pass/PassOrders.java
- vadl/test/resources/llvm/riscv/spike/rv64im/has_LP64macro.c
- vadl/test/resources/llvm/riscv/spike/rv64im/has__LP64__macro.c
- vadl/test/vadl/lcb/riscv/QemuRiscvSimulationTest.java
- vadl/test/vadl/lcb/riscv/riscv64/QemuRiscv64SimulationTest.java
Added tests to verify that the macros are defined. `__LP64__` is also used in the floor function in wikisort.
> lcb: Defined test macros __LP64__ and __LP64

- vadl/main/vadl/iss/passes/opDecomposition/Decomposer.java
- vadl/main/vadl/iss/passes/opDecomposition/IssOpDecompositionPass.java
- vadl/main/vadl/iss/passes/opDecomposition/decomposer/IDecomposer.java
- vadl/main/vadl/iss/passes/opDecomposition/decomposer/ShiftDecomposer.java
- vadl/main/vadl/utils/GraphUtils.java
- vadl/main/vadl/viam/Constant.java
- vadl/main/vadl/viam/graph/dependency/BuiltInCall.java
- vadl/main/vadl/viam/graph/dependency/SignExtendNode.java
- vadl/main/vadl/viam/graph/visualize/DotGraphVisualizer.java
- vadl/main/vadl/viam/passes/functionInliner/ArtificialResInlinerPass.java
- vadl/main/vadl/viam/passes/functionInliner/FieldAccessInlinerPass.java
- vadl/main/vadl/viam/passes/functionInliner/FunctionInlinerPass.java
- vadl/main/vadl/viam/passes/functionInliner/Inliner.java
- vadl/test/resources/testSource/sys/aarch64/virt.vadl
- vadl/test/vadl/iss/aarch64/IssA64InstrTest.java
- vadl/test/vadl/iss/passes/opDecomposition/IssOpDecompositionPassTest.java
This PR adds support for the `EXTR` instruction which contains a 128 bit LSR call. 
Thus, it is required to be decomposed, which is done by the new Decomposer.
> iss: Support EXTR instruction by adding LSR decomposer

- vadl/main/vadl/ast/vadl.ATG
- vadl/test/vadl/ast/MacroTests.java
Models can now return record types. #247
> parser: Add record returns to models

- vadl/main/vadl/ast/MacroExpander.java
- vadl/main/vadl/ast/SymbolTable.java
- vadl/main/vadl/ast/TypeChecker.java
Unfortunately we skipped annotations on encoding definitions, which screwed up the state for the type checker and caused an crash.
> parser: Fix crash with annotations on encodings

- docs/refman/aarch32.vadl
- docs/refman/tutorial.md
- sys/aarch64/aarch64.vadl
- sys/v-risc/VarRisc.vadl
- vadl/main/vadl/ast/AstVisitor.java
- vadl/main/vadl/ast/BehaviorLowering.java
- vadl/main/vadl/ast/ConstantEvaluator.java
- vadl/main/vadl/ast/Expr.java
- vadl/main/vadl/ast/MacroExpander.java
- vadl/main/vadl/ast/ParserUtils.java
- vadl/main/vadl/ast/TypeChecker.java
- vadl/main/vadl/ast/Ungrouper.java
- vadl/main/vadl/ast/vadl.ATG
- vadl/test/resources/macros/hexagon.vadl
- vadl/test/resources/testSource/sys/aarch64/aarch64.vadl
- vadl/test/resources/testSource/sys/risc-v/rvcsr.vadl
- vadl/test/resources/testSource/sys/v-risc/VarRisc.vadl
- vadl/test/vadl/ast/MacroTests.java
As discussed in #103 `AsStr` now also takes multiple arguments like `AsId`.
The PR also addresses an issue with `AsId` and now only allows valid identifiers. #82
> frontend: Rename ExtendId and IdToStr to AsId and AsStr

- vadl/main/vadl/ast/TypeChecker.java
Because the typechecker didn't return after handling one specific special case it sometimes continued with the generic case, resulting in the wrong type.
> typechecker: Fix wrong long multiply type

- vadl/main/vadl/iss/codegen/IssCMixins.java
- vadl/main/vadl/iss/passes/IssNormalizationPass.java
- vadl/main/vadl/iss/passes/IssTcgSchedulingPass.java
- vadl/main/vadl/iss/passes/TcgPassUtils.java
- vadl/main/vadl/iss/passes/nodes/IssSelectNode.java
- vadl/main/vadl/iss/passes/tcgLowering/TcgOpLoweringPass.java
- vadl/main/vadl/iss/passes/tcgLowering/nodes/TcgConstSelectNode.java
- vadl/main/vadl/viam/graph/control/DirectionalNode.java
- vadl/test/vadl/iss/IssInstrTest.java
- vadl/test/vadl/iss/IssLoweringTest.java
Select nodes that have a translation time constant condition, but with runtime options are now translated to a `tcg_gen_mov(<dest>, <c-cond> ? <true-case> : <false-case>` instead of a `tcg_gen_condmov`.
> iss: Optimize selects with constant condition

- vadl/main/resources/templates/iss/target/gen-arch/cpu.h
- vadl/main/vadl/iss/DataFlowAnalysis.java
- vadl/main/vadl/iss/passes/IssInfoRetrievalPass.java
- vadl/main/vadl/iss/passes/extensions/RegInfo.java
- vadl/main/vadl/viam/passes/statusBuiltInInlinePass/RemoveUnusedStatusFlagsFromBuiltinsPass.java
- vadl/test/resources/scripts/iss_qemu/main.py
- vadl/test/resources/testSource/sys/aarch64/aarch64.vadl
- vadl/test/resources/testSource/sys/aarch64/virt.vadl
- vadl/test/vadl/iss/AutoAssembler.java
- vadl/test/vadl/iss/aarch64/IssA64InstrTest.java
The CPU state register type was potentially smaller than the corresponding TCG variable, which caused an overflow when QEMU synchronized the TCG variable with the CPU state.
> iss: Fix CPU state register overflow

- sys/aarch64/aarch64.vadl
- vadl/main/vadl/lcb/codegen/expansion/CompilerInstructionExpansionCodeGenerator.java
- vadl/main/vadl/lcb/template/lib/Target/MCTargetDesc/EmitMCInstExpanderCppFilePass.java
- vadl/main/vadl/viam/graph/control/InstrCallNode.java
- vadl/test/vadl/lcb/riscv/riscv64/template/MCTargetDesc/EmitMCInstExpanderCppFilePassTest.java
This PR extends the MCInstExpander to support multiple fields in the decoding function.
> lcb: Extend MCInstExpander

- vadl/main/vadl/viam/graph/Graph.java
We drop the source code location at the moment. This PR extends the copy method to set location based on the copied node.
> viam: Keep source code location when copy

- vadl/main/vadl/lcb/passes/llvmLowering/strategies/LlvmInstructionLoweringStrategy.java
Removed it because it fills the entire screen with warnings for AArch64.
> lcb: Removed warning

- vadl-cosim/config.toml
- vadl-cosim/src/annotate-fields.py
- vadl-cosim/src/config.py
- vadl-cosim/src/cosimulation_broker.py
- vadl-cosim/src/cstructs.py
- vadl-cosim/src/qemu_ipc.py
- vadl-cosim/vadl-cosim.py
- vadl/main/resources/templates/iss/contrib/plugins/cosimulation.c
This PR implements cosimulation at the translation-block layer, both `tb` and `tb-strict` are added as values to the `testing.protocol.layer` configuration option:
- `tb-strict`: Assumes that equivalent translation-blocks are generated by all QEMU-clients - any divergences result in a test-fail.
- `tb`: Translation-blocks do not have to be equivalent, rather the PC is compared. This allows for clients with differently generated TBs but equivalent instructions. 
For `tb`, the clients currently synchronize as follows:
1. Each client gets one execution step, the PC before the exec and after is collected and added to a list.
2. After every client ran once, a call to `sync_clients` is made:
3. The largest PC (after exec-step) is selected.
4. All clients with a after-exec PC smaller than the …
> iss: Add TB-Layer to cosimulation

- vadl/main/resources/templates/lcb/llvm/lib/Target/AsmParser/AsmParser.cpp
- vadl/main/vadl/lcb/template/lib/Target/AsmParser/EmitAsmParserCppFilePass.java
- vadl/test/resources/llvm/riscv/asm/rv32im/codeemitter/UType.s
- vadl/test/resources/llvm/riscv/asm/rv32im/parser/BType.s
- vadl/test/resources/llvm/riscv/asm/rv32im/parser/JType.s
- vadl/test/resources/llvm/riscv/asm/rv32im/parser/UType.s
- vadl/test/resources/testSource/sys/risc-v/rv32im.vadl
This PR re-implements the immediate decoding in the assembly parser, which was missing after the refactorings of #361.
Note: This implementation only works for architectures where the decoding (= field access) functions only take a single field as input.
> asm: Fix immediate decoding in asm parser

- vadl/main/vadl/gcb/passes/IdentifyFieldUsagePass.java
- vadl/main/vadl/gcb/passes/operands/model/GcbInstructionImmediateOperand.java
- vadl/main/vadl/lcb/codegen/assembly/AssemblyInstructionPrinterImmediateHandler.java
- vadl/main/vadl/lcb/passes/llvmLowering/CreateFunctionsFromImmediatesPass.java
- vadl/main/vadl/lcb/passes/llvmLowering/tablegen/model/TableGenInstruction.java
- vadl/main/vadl/lcb/passes/llvmLowering/tablegen/model/tableGenOperand/TableGenInstructionLabelOperand.java
- vadl/main/vadl/lcb/passes/operands/TableGenInstructionImmediateOperand.java
- vadl/main/vadl/pass/PassOrders.java
- vadl/main/vadl/viam/Instruction.java
- vadl/main/vadl/viam/passes/SnapshotInstructionBehaviorPass.java
It adds a new pass to snapshot the instruction's behavior before any modification happens. Additionally, a few minor changes to spot an immediate before lowering were required.
Closes #387
> lcb: Bugfixes for aarch64

- vadl/main/vadl/viam/graph/dependency/SliceNode.java
When slice node's type has the same bounds like the value node, then the slice node is obsolete and can be deleted.
> viam: Added optimisation for SliceNode

- vadl/main/vadl/gcb/passes/MachineInstructionLabel.java
- vadl/main/vadl/lcb/passes/isaMatching/IsaMachineInstructionMatchingPass.java
- vadl/main/vadl/lcb/template/lib/Target/EmitInstrInfoCppFilePass.java
- vadl/main/vadl/viam/matching/impl/ReadRegisterCounterMatcher.java
- vadl/test/resources/testSource/lcb/riscv32_register_elimination.vadl
- vadl/test/vadl/lcb/aarch64/IsaMachineInstructionMatchingAarch64PassTest.java
This PR contains the following changes:
- adds the labelling of unconditional jumps in Aarch64 (machine instructions)
- it uses the machine instruction unconditional jump and if it cannot one then looks for a pseudo instruction unconditional jump. This covers both Aarch64 and RISCV.
- improves the heuristic to find the branch instruction's immediate and its bitwidth
> lcb: Bugfixes Aarch64

- vadl/main/vadl/viam/passes/NormalizeFieldsToFieldAccessFunctionsPass.java
When a field is used as immediate, we construct a field access function automatically. To avoid naming collisions, we have to change name otherwise the generated tablegen has duplicated entries.
> lcb: Fixed name of generated field access functions

- vadl/main/resources/templates/lcb/clang/lib/Basic/Targets/ClangTarget.cpp
- vadl/main/vadl/lcb/template/clang/lib/Basic/Targets/EmitClangTargetCppFilePass.java
We would need to extend the VADL lang to be able
to specify them correctly. Meanwhile, they are not really needed at the moment.
> lcb: Removed gcc reg aliases

- vadl/main/vadl/iss/passes/tcgLowering/TcgOpLoweringPass.java
There was a typo in the IssConstExtractNode lowering.
Instead of truncating the signed extracted value to the "toWidth", it truncated it to the "fromWidth" which is obviously false, as it essentially undos the sign extract.
> iss: Fix a wrong TCG operation lowering of a signed IssConstExtractNode

- vadl/main/vadl/ast/AstUtils.java
- vadl/main/vadl/ast/SymbolTable.java
- vadl/main/vadl/lcb/codegen/assembly/AssemblyInstructionPrinterCodeGeneratorVisitor.java
- vadl/main/vadl/lcb/codegen/assembly/AssemblyInstructionPrinterImmediateHandler.java
- vadl/main/vadl/lcb/codegen/assembly/ParserGenerator.java
- vadl/main/vadl/lcb/passes/llvmLowering/tablegen/lowering/TableGenInstAliasRenderer.java
- vadl/main/vadl/types/BuiltInTable.java
- vadl/test/vadl/ast/ParserTest.java
This PR closes #408.
It adds the `udec` and `sdec` built-ins. The old `decimal` built-in is removed but the name can stil be used as an alias for `sdec`. 
Once all specification were adapted, to used `udec`/`sdec`, we must also remove this alias (#409).
> frontend: Add udec/sdec and remove decimal built-in

- vadl/main/vadl/gcb/passes/DetermineRegisterUsesAndDefsPass.java
- vadl/main/vadl/gcb/passes/IsaMatchingUtils.java
- vadl/main/vadl/gcb/passes/MachineInstructionLabel.java
- vadl/main/vadl/gcb/passes/RegisterRef.java
- vadl/main/vadl/gcb/passes/operands/GenerateInstructionOperandsPass.java
- vadl/main/vadl/lcb/passes/isaMatching/IsaMachineInstructionMatchingPass.java
- vadl/main/vadl/lcb/passes/llvmLowering/LlvmLoweringPass.java
- vadl/main/vadl/lcb/passes/llvmLowering/domain/selectionDag/LlvmReadArtificialResourceNode.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/LlvmInstructionLoweringStrategy.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/instruction/LlvmInstructionLoweringIndirectJumpAndLinkStrategyImpl.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/instruction/LlvmInstructionLoweringUnconditionalIndirectJumpWithoutLinkRegistersStrategyImpl.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/instruction/LlvmInstructionLoweringUnconditionalJumpWithLinkRegistersStrategyImpl.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/nodeLowering/LcbNodeReplacementHandler.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/visitors/TableGenNodeVisitor.java
- vadl/main/vadl/lcb/passes/llvmLowering/tablegen/lowering/TableGenInstructionRenderer.java
- vadl/main/vadl/lcb/passes/llvmLowering/tablegen/lowering/TableGenPatternPrinterVisitor.java
- vadl/main/vadl/lcb/template/lib/Target/EmitRegisterInfoCppFilePass.java
- vadl/main/vadl/pass/PassOrders.java
- vadl/main/vadl/viam/graph/dependency/ReadArtificialResNode.java
- vadl/main/vadl/viam/graph/dependency/WriteArtificialResNode.java
- vadl/test/resources/snapshots/aarch64/RegisterInfo.cpp
- Fixed register names in instruction's uses and defs
- Fixed missing field accesses when they were optimised
- Make SliceNodes unlowerable
- At the moment, there was a set of instruction labels which all require a Frame-Index pattern. This is, however, not required in AArch64 since multiple instructions exist. So, we need only one pattern per instruction label.
> lcb: Fixes for Aarch64

- vadl/main/vadl/ast/AnnotationTable.java
- vadl/main/vadl/gcb/annotations/StatusRegisterAnnotation.java
- vadl/test/resources/testSource/sys/aarch64/aarch64.vadl
This PR adds new annotations to annotate status registers. This will come in handy when we need figure out the edge cases for non-default-flow pruning.
> ast: Added annotations for status registers

- vadl/main/vadl/gcb/passes/operands/GenerateInstructionOperandsPass.java
- vadl/main/vadl/gcb/passes/operands/model/GcbDefaultInstructionOperand.java
- vadl/test/resources/snapshots/aarch64/InstrInfoTableGen.td
The `BFMW` instruction has the register as output and input operand. This is not allowed. It was fixed by fixing the `.equals` method to filter duplicates.
```
def BFMW : Instruction
{
let Namespace = "aarch64temp";
let Size = 4;
let CodeSize = 4;
let OutOperandList = ( outs S:$rd );
let InOperandList = ( ins S:$rd, S:$rn, AArch64Base_BFMW_leftWSizeAsInt64:$leftWSize, AArch64Base_BFMW_rightWSizeAsInt64:$rightWSize );
```
The `MRS` instruction has the register multiple times as operand which is not allowed. We added a `distinct` to the stream.
```
def MRS : Instruction
{
let Namespace = "aarch64temp";
let Size = 4;
let CodeSize = 4;
let OutOperandList = ( outs S:$rt, S:$rt, S:$rt, S:$rt, S:$rt, S:$rt, S:$rt, S:$rt, S:$rt );
let InOperandList = ( ins AArch64Base_MRS_sysregAsInt64:$sysreg ); …
```
> gcb: Fix duplicated operands

- vadl/main/vadl/lcb/passes/isaMatching/IsaMachineInstructionMatchingPass.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/nodeLowering/LcbNodeReplacementHandler.java
- vadl/test/resources/snapshots/aarch64/InstrInfoTableGen.td
- vadl/test/resources/snapshots/rv64im/InstrInfoTableGen.td
Removed the typecasts because TableGen's typechecker doesn't allow them for AArch64. I don't know why.
```
def : Pat<(i64 (sextloadi32 (add X:$rs1, RV3264Base_LW_immSAsInt64:$immS))),
(LW X:$rs1, RV3264Base_LW_immSAsInt64:$immS)>;
```
> lcb: Removed typecasts before sign and zero extension

- vadl/main/vadl/lcb/passes/llvmLowering/LlvmLoweringPass.java
- vadl/test/resources/snapshots/aarch64/InstrInfoTableGen.td
We cannot create inst alias from arbitrary expressions. At the moment, the operand gets skipped, but this leads to a crash. Now, we are skipping the whole generation of the inst alias.
> lcb: Skip inst aliases when field assignment has expression

- vadl/main/vadl/lcb/passes/llvmLowering/LlvmLoweringPass.java
- vadl/test/resources/snapshots/aarch64/InstrInfoTableGen.td
- vadl/test/resources/snapshots/rv64im/InstrInfoTableGen.td
I removed the inst aliases because it is hard to support it when a field access function has multiple fields. It the current implementation, we would have added all the fields to the expanded code which is not correct and led to an error in AArch64.
> lcb: Removed inst aliases

- vadl/main/vadl/ast/AnnotationTable.java
- vadl/main/vadl/gcb/annotations/CompilerRegisterRenamingAnnotation.java
- vadl/main/vadl/gcb/annotations/HalfWidthOfAnnotation.java
- vadl/main/vadl/gcb/passes/ApplyCompilerRegisterRenamingPass.java
- vadl/main/vadl/gcb/passes/operands/model/GcbInstructionConcreteRegisterOperand.java
- vadl/main/vadl/iss/passes/IssGdbInfoExtractionPass.java
- vadl/main/vadl/lcb/passes/llvmLowering/domain/selectionDag/LlvmReadArtificialResourceNode.java
- vadl/main/vadl/lcb/passes/llvmLowering/strategies/instruction/LlvmInstructionLoweringFrameIndexHelper.java
- vadl/main/vadl/lcb/template/lib/Target/EmitInstrInfoCppFilePass.java
- vadl/main/vadl/lcb/template/lib/Target/EmitRegisterInfoCppFilePass.java
- vadl/main/vadl/pass/PassOrders.java
- vadl/main/vadl/viam/RegisterTensor.java
- vadl/main/vadl/viam/passes/staticCounterAccess/StaticCounterAccessResolvingPass.java
- vadl/test/resources/snapshots/aarch64/InstrInfoTableGen.td
- vadl/test/resources/testSource/sys/aarch64/aarch64.vadl
The problem is that the compiler generator requires two register classes `X` and `W` to properly generate AArch64 code. But this is not the format in which the instructions' behaviors are, so we need to adapt them. We do it by replacing it with artificial resources.
References #415
> ast+viam+lcb: Added annotations to rename registers

- vadl-cosim/cosim-lib/src/cosim/mod.rs
- vadl-cosim/cosim-lib/src/ipc/cstructs.rs
- vadl-cosim/cosim-lib/src/ipc/qemu.rs
- vadl-cosim/cosim-lib/src/ipc/sem.rs
- vadl-cosim/cosim-lib/src/ipc/shm.rs
- vadl-cosim/cosim-lib/src/trace/mod.rs
- vadl/main/resources/templates/iss/contrib/plugins/cosimulation.c
`libc::sem_timedwait` is not supported under darwin. While busy-waiting using `libc::sem_trywait` is possible, a cleaner solution is to migrate to `libc::pthread_mutex_t` and `libc::pthread_cond_t` which also have a `timedwait` implementation which is supported by darwin. The current implementation is only marginally slower compared to the original named-semaphore code  (460ms $\to$ 500ms).
> iss: Using pthread_mutex and pthread_cond instead of named semaphores to support cosimulation on darwin

- vadl-cosim/Cargo.lock
- vadl-cosim/broker/Cargo.toml
- vadl-cosim/broker/src/main.rs
- vadl-cosim/config.toml
- vadl-cosim/cosim-lib/src/cli/mod.rs
- vadl-cosim/cosim-lib/src/config/mod.rs
- vadl-cosim/cosim-lib/src/cosim/mod.rs
- vadl-cosim/cosim-lib/src/diff/diff.rs
- vadl-cosim/cosim-lib/src/diff/mod.rs
- vadl-cosim/cosim-lib/src/ipc/cstructs.rs
- vadl-cosim/cosim-lib/src/ipc/mod.rs
- vadl-cosim/cosim-lib/src/ipc/qemu.rs
- vadl-cosim/cosim-lib/src/ipc/sem.rs
- vadl-cosim/cosim-lib/src/ipc/shm.rs
- vadl-cosim/cosim-lib/src/lib.rs
- vadl-cosim/cosim-lib/src/trace/db.rs
- vadl-cosim/cosim-lib/src/trace/mod.rs
- vadl/main/resources/templates/iss/contrib/plugins/cosimulation.c
This PR more data to the cosimulation-report and also now prints the report in a json-format.
Specifically, the report now additionally contains:
- a "before" state of all the registers before a diff occurred
- the instruction that was executed which caused the diverging state
- the "after" state of all the registers when the diff occurred
for each client.
This feature initially slowed the cosimulator by a large amount - with the issue being that the whole before-state needed to be cloned / pre-computed before every iteration "just in case" a divergence occurred. This resulted in a lot of unnecessary cloning / data-transformations.
The final solution can be seen in the last commit (e5fd5c207bce832fcba7b9e49ebff9a85ee5753f): I introduce a second shared-memory object for each client and …
> iss: Added before->instruction->after state-transition to diff-context of the cosimulation-report

- vadl/test/resources/llvm/riscv/asm/rv32im/parser/IType.s
- vadl/test/resources/testSource/sys/risc-v/rv32im.vadl
This PR extends the `rv32im` assembly grammar so that the abbreviated form of  `JALR` can be parsed.
Before these forms could be parsed:
```
jalr x1, x2, 0
jalr x1, 0(x2)
```
Now also this form can be parsed:
```
jalr x2
```
> asm: Add abbreviated JALR form to rv32im asm grammar

- vadl/main/resources/templates/lcb/llvm/lib/Target/RegisterInfo.td
- vadl/main/vadl/gcb/passes/GenerateCompilerRegistersPass.java
- vadl/main/vadl/gcb/valuetypes/CompilerRegister.java
- vadl/main/vadl/gcb/valuetypes/ValueType.java
- vadl/main/vadl/lcb/passes/llvmLowering/GenerateTableGenRegistersPass.java
- vadl/main/vadl/lcb/passes/llvmLowering/tablegen/model/register/TableGenRegister.java
- vadl/test/resources/snapshots/aarch64/RegisterInfo.td
- vadl/test/vadl/lcb/riscv/riscv64/template/EmitRegisterInfoTableGenFilePassTest.java
Add alias registers as register classes which can be used in instruction selection. We have also to define relationships between the register classes since they reference the same hardware register file.
> lcb: Render alias registers as separate register class with subregister indexing

- sys/aarch64/aarch64.vadl
- vadl/test/resources/embench/build_virt-iss-a64.sh
- vadl/test/resources/snapshots/aarch64/InstrInfoTableGen.td
- vadl/test/resources/snapshots/aarch64/RegisterInfo.td
- vadl/test/resources/testSource/sys/aarch64/aarch64.vadl
The https://github.com/OpenVADL/openvadl/discussions/441 implemented sliced alias registers. This PR applies them for the `W` register.
> sys: Use W register in aarch64 specification

- vadl/main/resources/templates/lcb/llvm/lib/Target/RegisterInfo.td
- vadl/main/vadl/gcb/passes/GenerateCompilerRegistersPass.java
- vadl/main/vadl/gcb/valuetypes/CompilerRegister.java
- vadl/main/vadl/lcb/passes/llvmLowering/tablegen/model/register/TableGenRegister.java
- vadl/main/vadl/lcb/template/lib/Target/EmitRegisterInfoTableGenFilePass.java
- vadl/test/resources/snapshots/aarch64/RegisterInfo.td
- vadl/test/vadl/lcb/riscv/riscv64/template/EmitRegisterInfoTableGenFilePassTest.java
The `S` register has two aliases which are half the size. LLVM doesn't allow duplicates for the subRegIndex. So, we have to create multiple definitions.
> lcb: Defined multiple subreg index to allow aliases

- vadl/main/vadl/gcb/passes/operands/GenerateInstructionOperandsPass.java
- vadl/test/resources/snapshots/aarch64/InstrInfoTableGen.td
Before we filtered based on the name + type. Now, we only filter with the name.
> lcb: Fixed duplicated operands

- vadl-cli/main/vadl/cli/Utils.java
Extraction of the quemu source archive fails on Ubuntu 24.04.3 LTS, because the call of normalize() removes a preceeding './' from outputPath. This fails the comparison at line 161 with an IOException. Removing the normalize() call fixes the issue.
> cli: Fix qemu source archive extraction

- build.gradle.kts
When executing commands that require user input through the Gradle wrapper, an error occurs because System.in is not connected to the console.
Example Command:
```
./gradlew run --args="iss --init sys/ppc64/ppc64.vadl"
```
Output:
```
...
Do you trust this source? (y/n): Error: No line found
FAILURE: Build failed with an exception.
```
This is fixed by setting standardInput = System.in in build.gradle.kts.
> gradle: Enable console input for gradlew run tasks

- vadl-cosim/broker/src/main.rs
- vadl-cosim/config.toml
- vadl-cosim/cosim-lib/src/config/mod.rs
- vadl-cosim/cosim-lib/src/ipc/qemu.rs
This doesn't change any behaviour of the broker but simply allows to use different test-execs per client (e.g. in case of different endianess between upstream and vadl iss versions). 
Now, in the config-file, the `test_exec` field is moved to `qemu.client.test_exec`, and the cli now can take multiple `--test-exec` options; one for each client (if only one `--test-exec` is provided, then all clients will receive the same executable).
> iss: Changed cosimulation config to be able to take a test-executable per client

- vadl/main/resources/templates/lcb/llvm/lib/Target/ISelLowering.cpp
- vadl/main/vadl/lcb/template/lib/Target/EmitISelLoweringCppFilePass.java
If we have an architecture with `i64` then we also need to handle `i32`. In rv64im, this wasn't really a problem, but somehow in AArch64 it is.
> lcb: Set types for branch lowering
